[package]
name = "tendermint-sys"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ffi-support = "0.4.3"
tendermint = "0.20.0"
tendermint-abci = "0.20.0"
